In [2]:
# Importing Numpy
import numpy as np

In [2]:
# Initializing from Python List
v = np.array([1,4,9,3,2])
print ('1D array in numpy is %s\n'%v)
print ('dtype of the numpy array is %s\n'%str(v.dtype))
print ('shape of the numpy array is %s\n'%v.shape)

1D array in numpy is [1 4 9 3 2]

dtype of the numpy array is int32

shape of the numpy array is 5



In [3]:
v1 = np.arange(5)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,5)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-10,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)



Creating a numpy array via arange (stop=5) : [0 1 2 3 4]

Creating a numpy array via arange (start=2,stop=5) : [2 3 4]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6 -8]



In [5]:
pymat = [[1,2,3],[4,5,6]]
npmat = np.array(pymat)
print ('numpy matrix is \n%s\n'%npmat)
print ('Flattened version of numpy matrix is %s\n'%npmat.flatten())
# By flatten the matrix becomes row major 1D vector (This is the way in which a matrix is stored in memory). 


numpy matrix is 
[[1 2 3]
 [4 5 6]]

Flattened version of numpy matrix is [1 2 3 4 5 6]



In [6]:
mat_zeros = np.zeros(shape=(4,6))
print ('Zeros Matris of shape %s is \n%s\n'%(mat_zeros.shape,mat_zeros))
mat_ones = np.ones(shape=(5,3))
print ('Ones Matris of shape %s is \n%s\n'%(mat_ones.shape,mat_ones))


Zeros Matris of shape (4, 6) is 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Ones Matris of shape (5, 3) is 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [12]:
#Using numpy.random.random
mat1 = np.random.random(size=(3,4))
print ('matrix generated from numpy.random.random is \n%s\n'%mat1)
mat2 = np.random.randint(low=0,high=2,size=(3,4))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)
mat3 = np.random.randn(4,4)
print ('matrix generated from numpy.random.randn is \n%s\n'%mat3)


matrix generated from numpy.random.random is 
[[0.83055125 0.5711236  0.01332212 0.2630037 ]
 [0.08317542 0.35058843 0.4850059  0.62343358]
 [0.50599417 0.9540652  0.47214664 0.56440543]]

matrix generated from numpy.random.random is 
[[1 1 1 0]
 [1 0 1 1]
 [1 1 0 0]]

matrix generated from numpy.random.randn is 
[[ 0.89052737 -0.92848003  0.40289455  1.1265508 ]
 [ 1.21486255 -0.22076839 -0.73046807 -1.53697979]
 [-0.5611523   0.72090034 -0.75867721  0.12431961]
 [ 1.45912549 -0.0253539  -0.53796178  0.79451129]]



In [13]:
vec = np.arange(10)
vec1 = vec[:-3]
print ('Result of removing last 3 elements from range(10) : \n%s\n'%vec1)

Result of removing last 3 elements from range(10) : 
[0 1 2 3 4 5 6]



In [14]:

vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::2]
print ('Elements at even indices are %s\n'%vec2)


Original array is [ 0  3  6  9 12 15 18]

Elements at even indices are [ 0  6 12 18]



In [15]:
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::-1]
print ('Elements for indices in reverse is %s\n'%vec2)

Original array is [ 0  3  6  9 12 15 18]

Elements for indices in reverse is [18 15 12  9  6  3  0]



In [16]:
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[2:5]
print ('Elements for indices 2:5 is %s\n'%vec2)

Original array is [ 0  3  6  9 12 15 18]

Elements for indices 2:5 is [ 6  9 12]



In [17]:
idx=[0,1,5]
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[idx]
print ('Subarray constructed by indices %s is %s\n'%(idx,vec2))

Original array is [ 0  3  6  9 12 15 18]

Subarray constructed by indices [0, 1, 5] is [ 0  3 15]



In [18]:
mat = np.random.randint(0,6,(3,5))
# Create a submatrix with first 2 rows and last 2 columns
submat1 = mat[0:2,-2:]
print ('Original Matrix is \n%s\n'%mat)
print ('Sub Matrix with first 2 rows and last 2 columns is \n%s\n'%submat1)
submat2 = mat[:,3:0:-1]
print ('After flipping the columns of the matrix, it looks : \n%s\n'%submat2)

Original Matrix is 
[[4 5 4 2 0]
 [2 0 2 5 0]
 [0 1 2 5 3]]

Sub Matrix with first 2 rows and last 2 columns is 
[[2 0]
 [5 0]]

After flipping the columns of the matrix, it looks : 
[[2 4 5]
 [5 2 0]
 [5 2 1]]



In [19]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2,sp3 = np.hsplit(mat,[3,6])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))
print ('Third split of shape %s, is \n%s\n'%(sp3.shape,sp3))

Original matrix of shape (3, 7), is 
[[2 1 3 2 3 5 5]
 [1 3 0 3 0 5 2]
 [0 5 4 2 4 3 1]]

First split of shape (3, 3), is 
[[2 1 3]
 [1 3 0]
 [0 5 4]]

Second split of shape (3, 3), is 
[[2 3 5]
 [3 0 5]
 [2 4 3]]

Third split of shape (3, 1), is 
[[5]
 [2]
 [1]]



In [24]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2 = np.vsplit(mat,[1])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))

Original matrix of shape (3, 7), is 
[[4 4 5 2 5 4 4]
 [3 0 3 1 3 3 5]
 [2 0 0 1 2 1 3]]

First split of shape (1, 7), is 
[[4 4 5 2 5 4 4]]

Second split of shape (2, 7), is 
[[3 0 3 1 3 3 5]
 [2 0 0 1 2 1 3]]



In [31]:
mat1 = np.random.random((2,3))
pt1 = mat1[0].__array_interface__['data'][0]
print ('Memory Location of mat1[0] is : %s\n'%pt1)
pt2 = mat1[1].__array_interface__['data'][0]
print ('Memory Location of mat1[1] is : %s\n'%pt2)
print ('Difference in Memory Location for 3 elements  is : %s bytes\n'%(pt2-pt1))
print ('Memory jump = 8 bytes')


Memory Location of mat1[0] is : 126210144

Memory Location of mat1[1] is : 126210168

Difference in Memory Location for 3 elements  is : 24 bytes

Memory jump = 8 bytes


In [34]:
def identity(elem):
    return elem
v = np.array([1,2,3])
v1 = v # Copy by reference
v1[1]=10
print ('Value of v, after v1 is modified is %s\n'%v)
# Pass by Function 
v = np.array([1,2,3])
v1 = identity(v) # Copy by reference
v1[0]=20
print ('Value of v after func(v) is modified is %s\n'%v)
v = np.array([1,2,3])
v1 = v.copy() # Copy by reference
v1[0]=10
print ('Value of v after v.copy() is modified is %s\n'%v)

Value of v, after v1 is modified is [ 1 10  3]

Value of v after func(v) is modified is [20  2  3]

Value of v after v.copy() is modified is [1 2 3]



In [35]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ('Original Matrix is \n%s\n'%mat)

#1 Add 10 to all the even indexes in matrix
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1 = mat[::2,::2]
mat1+=10
print (' Matrix with 10 added to even indices is \n%s\n'%mat1)
# Changes in mat1 are reflected in mat. This happens because the default assignment in numpy is 'pass by reference'

Original Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Matrix with 10 added to even indices is 
[[11 13]
 [17 19]]



In [36]:
mat = np.random.randint(0,6,(3,5))
print ('mat is \n%s\n'%mat)
v = np.array([10,20,30,40,50])
print ('v is \n%s\n'%v)
print ('mat+1 is \n%s\n'%(mat+1)) # Similar behaviour in case of np.array([1])
print ('mat+v is \n%s\n'%(mat+v))
print ('mat*v is \n%s\n'%(mat*v))
print ('mat+mat is \n%s\n'%(mat+mat))
print ('mat*mat is \n%s\n'%(mat*mat))


mat is 
[[4 5 0 0 3]
 [3 4 4 2 2]
 [2 0 0 4 2]]

v is 
[10 20 30 40 50]

mat+1 is 
[[5 6 1 1 4]
 [4 5 5 3 3]
 [3 1 1 5 3]]

mat+v is 
[[14 25 30 40 53]
 [13 24 34 42 52]
 [12 20 30 44 52]]

mat*v is 
[[ 40 100   0   0 150]
 [ 30  80 120  80 100]
 [ 20   0   0 160 100]]

mat+mat is 
[[ 8 10  0  0  6]
 [ 6  8  8  4  4]
 [ 4  0  0  8  4]]

mat*mat is 
[[16 25  0  0  9]
 [ 9 16 16  4  4]
 [ 4  0  0 16  4]]



In [37]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])
vec2 = np.array([2,4,6])
print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector dot product is <v1,v2> is %s\n'%np.dot(vec1,vec2))
print ('---------------\n')

print ('Matrix is\n%s\n'%mat)
print ('Vector v2 is\n%s\n'%vec1)

print ('Matrix Vector product is <mat,vec1> is \n%s\n'%np.dot(mat,vec1))
print ('Matrix Matrix multiplication is <mat,mat> is \n%s\n'%np.dot(mat,mat))
print ('---------------\n')

print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector outer product is <v1,v2> is \n%s\n'%np.outer(vec1,vec2))


Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector dot product is <v1,v2> is 28

---------------

Matrix is
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Vector v2 is
[1 2 3]

Matrix Vector product is <mat,vec1> is 
[ 8 26 44]

Matrix Matrix multiplication is <mat,mat> is 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

---------------

Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector outer product is <v1,v2> is 
[[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]



1.7 Statistical Functions

In [3]:
mat = np.arange(9).reshape((3,3))
print ('Original matrix is \n%s\n'%mat)
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0))
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))
print ('---------------------------\n')
print ('Overall varience of matrix is %s\n'%np.var(mat))
print ('Overall sum of matrix is %s\n'%np.sum(mat))
print ('Overall min of matrix is %s\n'%np.min(mat))
print ('Overall max of matrix is %s\n'%np.max(mat))

print ('-------------------------------------\n')
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))


Original matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Overall mean of matrix is 
4.0

Row mean of matrix is 
[3. 4. 5.]

Column mean of matrix is 
[1. 4. 7.]

---------------------------

Overall varience of matrix is 6.666666666666667

Overall sum of matrix is 36

Overall min of matrix is 0

Overall max of matrix is 8

-------------------------------------

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



In [4]:
ndmat = np.zeros(shape=(1,2,3,1))
print ('Original Shape of ndmat is %s\n'%str(ndmat.shape))
ndmat1 = np.squeeze(ndmat)
print ('Shape of np.squeeze(ndmat) is %s\n'%str(ndmat1.shape))
ndmat2 = np.squeeze(ndmat,axis=3)
print ('Shape of np.squeeze(ndmat,axis=3) is %s\n'%str(ndmat2.shape))



Original Shape of ndmat is (1, 2, 3, 1)

Shape of np.squeeze(ndmat) is (2, 3)

Shape of np.squeeze(ndmat,axis=3) is (1, 2, 3)



In [5]:
mat = np.zeros(shape=(2,3))
print ('Original Shape of 2D matrix is %s\n'%str(mat.shape))
mat_transpose = np.transpose(mat)
print ('Shape of np.transpose(mat) is %s\n'%str(mat_transpose.shape))
mat_transpose[1,0] = 1
print ('np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix\n')
print ('---------------------------------\n')
# NDimensional matrix
ndmat = np.zeros(shape=(2,3,4))
print ('Original Shape of nDimensional matrix is %s\n'%str(ndmat.shape))
ndmat_transpose = np.transpose(ndmat)
print ('Shape of np.transpose(ndmat) is %s\n'%str(ndmat_transpose.shape))
ndmat_special_transpose = np.transpose(ndmat, axes = [0,2,1])
print ('Shape of np.transpose(ndmat, axes=[0,2,1]) is %s\n'%str(ndmat_special_transpose.shape))


Original Shape of 2D matrix is (2, 3)

Shape of np.transpose(mat) is (3, 2)

np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix

---------------------------------

Original Shape of nDimensional matrix is (2, 3, 4)

Shape of np.transpose(ndmat) is (4, 3, 2)

Shape of np.transpose(ndmat, axes=[0,2,1]) is (2, 4, 3)

